version: 0.0.1.{branch}-{build}
environment:
  nodejs_version: "6"
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
install:
  - ps: Install-Product node $env:nodejs_version
init:
- cmd:
nuget:
  disable_publish_on_pr: true
before_build:
- cmd:
build_script:
- cmd: build.cmd %appveyor_build_version%
artifacts:
  - path: 'vscode-extension\*.vsix'
test: off
